package Enumeradores;

public enum Centros {
    NO_ESPECIFICADO,
    HOSPITAL_UNIVERSITARIO_LA_PAZ,
    HOSPITAL_UNIVERSITARIO_12_DE_OCTUBRE,
    HOSPITAL_UNIVERSITARIO_RAMON_Y_CAJAL,
    HOSPITAL_UNIVERSITARIO_GREGORIO_MARANON,
    HOSPITAL_UNIVERSITARIO_CLINICO_SAN_CARLOS,
    HOSPITAL_UNIVERSITARIO_DE_FUENLABRADA,
    HOSPITAL_UNIVERSITARIO_DE_GETAFE,
    HOSPITAL_UNIVERSITARIO_DE_MOSTOLES,
    HOSPITAL_UNIVERSITARIO_INFANTA_SOFIA,
    HOSPITAL_UNIVERSITARIO_INFANTA_CRISTINA,
    HOSPITAL_UNIVERSITARIO_INFANTA_ELENA,
    HOSPITAL_UNIVERSITARIO_PRINCIPE_DE_ASTURIAS,
    HOSPITAL_UNIVERSITARIO_SURESTE,
    HOSPITAL_UNIVERSITARIO_HENARES,
    HOSPITAL_UNIVERSITARIO_TORREJON,
}