package Enumeradores;

public enum Especialidades {
    NO_ESPECIFICADO,
    ENFERMERO,
    GENERAL,
    CARDIOLOGIA,
    PEDIATRIA,
    NEUROLOGIA,
    PSIQUIATRIA,
    UROLOGIA,
    GINECOLOGIA,
    OBSTETRICIA,
    OFTALMOLOGIA,
    OTORRINOLARINGOLOGIA,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    NEFROLOGIA,
    NEUMOLOGIA,
    REUMATOLOGIA,
    HEMATOLOGIA,
    ONCOLOGIA,
    ALERGOLOGIA,
    INFECTOLOGIA,

}
